use_frameworks!

target 'Omocodia_Example' do
  pod 'Omocodia', :path => '../'

  target 'Omocodia_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
